# Generated by Django 5.2.16 on 2026-07-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveSmallIntegerField()),
                ('defender_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winning_rule', models.CharField(choices=[('high', '높은 숫자 승리'), ('low', '낮은 숫자 승리')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '반격 대기'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=10)),
                ('attacker_score_change', models.IntegerField(default=0)),
                ('defender_score_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacked_games', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defended_games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
